sudo: required
language: node_js
node_js:
  - '9'
services:
  - docker
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
    - /^v[0-9]+\.[0-9]+\.[0-9]+-staging$/
stages:
  - build
  - hub
  - deploy
jobs:
  include:
    - stage: build
      if: branch = master
      install: skip
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build --tag pyrrha_boxplorer .
        - docker images
    - stage: build_prod
      if: branch =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      install: skip
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build --tag pyrrha_boxplorer .
        - docker images
        - docker tag pyrrha_boxplorer pandoraboxchain/pyrrha_boxplorer:latest
        - docker push pandoraboxchain/pyrrha_boxplorer:latest
    - stage: build_staging
      if: branch =~ /^v[0-9]+\.[0-9]+\.[0-9]+-staging$/
      install: skip
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build --tag pyrrha_boxplorer .
        - docker images
        - docker tag pyrrha_boxplorer pandoraboxchain/pyrrha_boxplorer:staging
        - docker push pandoraboxchain/pyrrha_boxplorer:staging
    - stage: deploy_prod
      if: branch =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      install: skip
      script:
        - openssl aes-256-cbc -K $encrypted_d7f89b072dc3_key -iv $encrypted_d7f89b072dc3_iv -in key.enc -out key -d
        - chmod 600 ./key
        - ssh -o "StrictHostKeyChecking no" -i ./key kostysh@pandora.network -tt 'bash -s' < ./deploy.sh
    - stage: deploy_staging
      if: branch =~ /^v[0-9]+\.[0-9]+\.[0-9]+-staging$/
      install: skip
      script:
        - openssl aes-256-cbc -K $encrypted_d7f89b072dc3_key -iv $encrypted_d7f89b072dc3_iv -in key.enc -out key -d
        - chmod 600 ./key
        - ssh -o "StrictHostKeyChecking no" -i ./key kostysh@boxplorer.staging.pandora.network -tt 'bash -s' < ./deploy-staging.sh
